TWSE_DAILY_TRADING_SOURCE_NAME = "TWSE OpenAPI Daily Trading"
TPEX_DAILY_QUOTES_SOURCE_NAME = "TPEx Mainboard Daily Quotes"

TWSE_COMPANY_PROFILE_SOURCE_NAME = "TWSE Listed Company Profile"
TPEX_DOMESTIC_COMPANY_PROFILE_SOURCE_NAME = "TPEx Domestic Company Profile"
TPEX_FOREIGN_COMPANY_PROFILE_SOURCE_NAME = "TPEx Foreign Company Profile"
