type WidenColorValues<T> = {
  readonly [K in keyof T]: T[K] extends string
    ? string
    : T[K] extends Record<string, unknown>
      ? WidenColorValues<T[K]>
      : T[K];
};

export const omiBaseColors = {
  surface: "#ffffff",
  surfaceSubtle: "#f8fafc",
  surfaceMuted: "#f1f5f9",
  surfaceStrong: "#e2e8f0",
  borderSubtle: "#e2e8f0",
  border: "#cbd5e1",
  borderStrong: "#94a3b8",
  text: "#0f172a",
  textMuted: "#64748b",
  textSubtle: "#94a3b8",
  control: "#0f172a",
  marketUp: "#dc2626",
  marketUpFlash: "#ef4444",
  marketDown: "#059669",
  marketDownFlash: "#10b981",
  warning: "#f59e0b",
  heatSoft: "#fff7ed",
  heat: "#f97316",
  heatMuted: "#fdba74",
  info: "#2563eb",
  infoSoftLine: "#93c5fd",
  cyan: "#0891b2",
  sky: "#0ea5e9",
  skyDark: "#0369a1",
  teal: "#0f766e",
  tealBright: "#14b8a6",
  green: "#16a34a",
  lime: "#65a30d",
  indigo: "#4f46e5",
  purple: "#7c3aed",
  purpleLight: "#a855f7",
  purpleAlt: "#9333ea",
  fuchsia: "#c026d3",
  pink: "#db2777",
  rose: "#f43f5e",
  roseDark: "#be185d",
  brown: "#92400e",
  amberDark: "#b45309",
  tooltip: "#6b7280",
  growth: "#ff5b5b",
} as const;

export type OmiBaseColors = WidenColorValues<typeof omiBaseColors>;

export const omiDarkBaseColors: OmiBaseColors = {
  surface: "#111720",
  surfaceSubtle: "#151d28",
  surfaceMuted: "#1b2533",
  surfaceStrong: "#263244",
  borderSubtle: "#202a39",
  border: "#2c384a",
  borderStrong: "#4b5b70",
  text: "#e2e8f0",
  textMuted: "#98a7b9",
  textSubtle: "#6f8094",
  control: "#202a39",
  marketUp: "#ef535c",
  marketUpFlash: "#ff7f86",
  marketDown: "#17a28d",
  marketDownFlash: "#45d3bd",
  warning: "#fbbf24",
  heatSoft: "#2a160b",
  heat: "#df7a2a",
  heatMuted: "#fed7aa",
  info: "#3f83e8",
  infoSoftLine: "#6aa8f8",
  cyan: "#38c7d9",
  sky: "#48b8e8",
  skyDark: "#6aa8f8",
  teal: "#39c7b5",
  tealBright: "#45d3bd",
  green: "#54c87a",
  lime: "#a3cf3a",
  indigo: "#8c98f4",
  purple: "#a997f4",
  purpleLight: "#bd94f2",
  purpleAlt: "#bd94f2",
  fuchsia: "#dd8aef",
  pink: "#f472b6",
  rose: "#fb7185",
  roseDark: "#fb7185",
  brown: "#d08c4f",
  amberDark: "#f59e4b",
  tooltip: "#b8c4d4",
  growth: "#ff7f86",
};

export const omiChartColors = {
  background: omiBaseColors.surface,
  surface: omiBaseColors.surface,
  surfaceSubtle: omiBaseColors.surfaceSubtle,
  grid: omiBaseColors.borderSubtle,
  gridSubtle: omiBaseColors.surfaceMuted,
  axisBorder: "#dbe3ef",
  text: omiBaseColors.text,
  textMuted: omiBaseColors.textMuted,
  textSubtle: omiBaseColors.textSubtle,
  control: omiBaseColors.control,
  marketUp: omiBaseColors.marketUp,
  marketUpFlash: omiBaseColors.marketUpFlash,
  marketUpVolume: "rgba(220, 38, 38, 0.24)",
  marketUpHistogram: "rgba(220, 38, 38, 0.35)",
  marketDown: omiBaseColors.marketDown,
  marketDownFlash: omiBaseColors.marketDownFlash,
  marketDownVolume: "rgba(5, 150, 105, 0.24)",
  marketDownHistogram: "rgba(5, 150, 105, 0.35)",
  crosshair: omiBaseColors.textSubtle,
  crosshairLabel: omiBaseColors.text,
  tooltip: omiBaseColors.tooltip,
  tooltipBorder: omiBaseColors.border,
  neutralLine: "#334155",
  neutralMuted: "#475569",
  info: omiBaseColors.info,
  warning: omiBaseColors.warning,
  cyan: omiBaseColors.cyan,
  sky: omiBaseColors.sky,
  skyDark: omiBaseColors.skyDark,
  teal: omiBaseColors.teal,
  tealBright: omiBaseColors.tealBright,
  green: omiBaseColors.green,
  lime: omiBaseColors.lime,
  indigo: omiBaseColors.indigo,
  purple: omiBaseColors.purple,
  purpleLight: omiBaseColors.purpleLight,
  purpleAlt: omiBaseColors.purpleAlt,
  fuchsia: omiBaseColors.fuchsia,
  pink: omiBaseColors.pink,
  rose: omiBaseColors.rose,
  roseDark: omiBaseColors.roseDark,
  brown: omiBaseColors.brown,
  amberDark: omiBaseColors.amberDark,
  heatSoft: omiBaseColors.heatSoft,
  heat: omiBaseColors.heat,
  heatMuted: omiBaseColors.heatMuted,
  growth: omiBaseColors.growth,
  cumulative: omiBaseColors.infoSoftLine,
  volume: "rgba(100, 116, 139, 0.18)",
  volumeStrong: "rgba(100, 116, 139, 0.35)",
  indicator: {
    maShort: omiBaseColors.info,
    maMiddle: omiBaseColors.warning,
    maLong: omiBaseColors.purpleLight,
    emaFast: omiBaseColors.cyan,
    emaSlow: omiBaseColors.rose,
    wma: omiBaseColors.sky,
    hma: omiBaseColors.roseDark,
    vwma: omiBaseColors.green,
    bollinger: "#0284c7",
    bollingerMiddle: "#38bdf8",
    vwap: "#334155",
    psar: omiBaseColors.purple,
    donchian: omiBaseColors.lime,
    ichimokuConversion: omiBaseColors.marketUp,
    ichimokuBase: omiBaseColors.info,
    ichimokuSpanA: omiBaseColors.marketDown,
    ichimokuSpanB: omiBaseColors.amberDark,
    ichimokuLagging: omiBaseColors.textMuted,
    keltner: omiBaseColors.teal,
    keltnerMiddle: omiBaseColors.tealBright,
    pivot: "#475569",
    rsi: omiBaseColors.fuchsia,
    macd: omiBaseColors.info,
    macdSignal: omiBaseColors.warning,
    momentum: "#0e7490",
    tsi: omiBaseColors.purple,
    awesomeOscillator: omiBaseColors.pink,
    ultimateOscillator: omiBaseColors.purpleAlt,
    atr: omiBaseColors.heat,
    stdDev: "#334155",
    choppiness: omiBaseColors.brown,
    obv: "#334155",
    obvMa: omiBaseColors.warning,
    mfi: omiBaseColors.teal,
    cmf: omiBaseColors.marketDown,
    adLine: "#475569",
    pvt: omiBaseColors.skyDark,
    relativeStrength: omiBaseColors.purple,
    beta: omiBaseColors.teal,
    correlation: omiBaseColors.skyDark,
    cci: omiBaseColors.indigo,
    williamsR: omiBaseColors.pink,
    roc: "#0e7490",
    trix: omiBaseColors.purple,
    trixSignal: omiBaseColors.warning,
  },
  drawing: {
    anchorVwap: omiBaseColors.cyan,
    volumeProfileRange: "#475569",
    priceRange: omiBaseColors.textMuted,
    measure: "#334155",
    rectangle: omiBaseColors.info,
    fibonacci: omiBaseColors.purple,
    ray: omiBaseColors.teal,
    default: omiBaseColors.text,
    selected: omiBaseColors.marketUp,
    hovered: omiBaseColors.info,
    handleBorder: omiBaseColors.surface,
  },
} as const;

export type OmiChartColors = WidenColorValues<typeof omiChartColors>;
export type OmiTheme = "light" | "dark";

export const omiDarkChartColors: OmiChartColors = {
  background: omiDarkBaseColors.surface,
  surface: omiDarkBaseColors.surface,
  surfaceSubtle: omiDarkBaseColors.surfaceSubtle,
  grid: omiDarkBaseColors.borderSubtle,
  gridSubtle: omiDarkBaseColors.surfaceMuted,
  axisBorder: omiDarkBaseColors.border,
  text: omiDarkBaseColors.text,
  textMuted: omiDarkBaseColors.textMuted,
  textSubtle: omiDarkBaseColors.textSubtle,
  control: omiDarkBaseColors.control,
  marketUp: omiDarkBaseColors.marketUp,
  marketUpFlash: omiDarkBaseColors.marketUpFlash,
  marketUpVolume: "rgba(239, 83, 92, 0.22)",
  marketUpHistogram: "rgba(239, 83, 92, 0.34)",
  marketDown: omiDarkBaseColors.marketDown,
  marketDownFlash: omiDarkBaseColors.marketDownFlash,
  marketDownVolume: "rgba(23, 162, 141, 0.22)",
  marketDownHistogram: "rgba(23, 162, 141, 0.34)",
  crosshair: omiDarkBaseColors.textSubtle,
  crosshairLabel: omiDarkBaseColors.text,
  tooltip: omiDarkBaseColors.tooltip,
  tooltipBorder: omiDarkBaseColors.borderStrong,
  neutralLine: "#b8c4d4",
  neutralMuted: omiDarkBaseColors.textMuted,
  info: omiDarkBaseColors.info,
  warning: omiDarkBaseColors.warning,
  cyan: omiDarkBaseColors.cyan,
  sky: omiDarkBaseColors.sky,
  skyDark: omiDarkBaseColors.skyDark,
  teal: omiDarkBaseColors.teal,
  tealBright: omiDarkBaseColors.tealBright,
  green: omiDarkBaseColors.green,
  lime: omiDarkBaseColors.lime,
  indigo: omiDarkBaseColors.indigo,
  purple: omiDarkBaseColors.purple,
  purpleLight: omiDarkBaseColors.purpleLight,
  purpleAlt: omiDarkBaseColors.purpleAlt,
  fuchsia: omiDarkBaseColors.fuchsia,
  pink: omiDarkBaseColors.pink,
  rose: omiDarkBaseColors.rose,
  roseDark: omiDarkBaseColors.roseDark,
  brown: omiDarkBaseColors.brown,
  amberDark: omiDarkBaseColors.amberDark,
  heatSoft: omiDarkBaseColors.heatSoft,
  heat: omiDarkBaseColors.heat,
  heatMuted: omiDarkBaseColors.heatMuted,
  growth: omiDarkBaseColors.growth,
  cumulative: omiDarkBaseColors.infoSoftLine,
  volume: "rgba(152, 167, 185, 0.16)",
  volumeStrong: "rgba(152, 167, 185, 0.3)",
  indicator: {
    maShort: omiDarkBaseColors.info,
    maMiddle: omiDarkBaseColors.warning,
    maLong: omiDarkBaseColors.purpleLight,
    emaFast: omiDarkBaseColors.cyan,
    emaSlow: omiDarkBaseColors.rose,
    wma: omiDarkBaseColors.sky,
    hma: omiDarkBaseColors.roseDark,
    vwma: omiDarkBaseColors.green,
    bollinger: omiDarkBaseColors.sky,
    bollingerMiddle: omiDarkBaseColors.cyan,
    vwap: "#b8c4d4",
    psar: omiDarkBaseColors.purple,
    donchian: omiDarkBaseColors.lime,
    ichimokuConversion: omiDarkBaseColors.marketUp,
    ichimokuBase: omiDarkBaseColors.info,
    ichimokuSpanA: omiDarkBaseColors.marketDown,
    ichimokuSpanB: omiDarkBaseColors.amberDark,
    ichimokuLagging: omiDarkBaseColors.textMuted,
    keltner: omiDarkBaseColors.teal,
    keltnerMiddle: omiDarkBaseColors.tealBright,
    pivot: omiDarkBaseColors.textMuted,
    rsi: omiDarkBaseColors.fuchsia,
    macd: omiDarkBaseColors.info,
    macdSignal: omiDarkBaseColors.warning,
    momentum: omiDarkBaseColors.cyan,
    tsi: omiDarkBaseColors.purple,
    awesomeOscillator: omiDarkBaseColors.pink,
    ultimateOscillator: omiDarkBaseColors.purpleAlt,
    atr: omiDarkBaseColors.heat,
    stdDev: "#b8c4d4",
    choppiness: omiDarkBaseColors.brown,
    obv: "#b8c4d4",
    obvMa: omiDarkBaseColors.warning,
    mfi: omiDarkBaseColors.teal,
    cmf: omiDarkBaseColors.marketDown,
    adLine: omiDarkBaseColors.textMuted,
    pvt: omiDarkBaseColors.skyDark,
    relativeStrength: omiDarkBaseColors.purple,
    beta: omiDarkBaseColors.teal,
    correlation: omiDarkBaseColors.skyDark,
    cci: omiDarkBaseColors.indigo,
    williamsR: omiDarkBaseColors.pink,
    roc: omiDarkBaseColors.cyan,
    trix: omiDarkBaseColors.purple,
    trixSignal: omiDarkBaseColors.warning,
  },
  drawing: {
    anchorVwap: omiDarkBaseColors.cyan,
    volumeProfileRange: omiDarkBaseColors.textMuted,
    priceRange: omiDarkBaseColors.textMuted,
    measure: "#b8c4d4",
    rectangle: omiDarkBaseColors.info,
    fibonacci: omiDarkBaseColors.purple,
    ray: omiDarkBaseColors.teal,
    default: omiDarkBaseColors.text,
    selected: omiDarkBaseColors.marketUp,
    hovered: omiDarkBaseColors.info,
    handleBorder: omiDarkBaseColors.surface,
  },
};

export function getOmiChartColors(theme: OmiTheme | string | null | undefined): OmiChartColors {
  return theme === "dark" ? omiDarkChartColors : omiChartColors;
}
